#!/bin/sh

java -cp src:jar/ant.jar:jar/jaxen-core.jar:jar/jaxen-jdom.jar:jar/jdom.jar:jar/pircbot.jar:jar/rome-1.0.jar:jar/rome-fetcher-1.0.jar:jar/saxpath.jar:jar/xalan.jar:jar/xerces.jar:jar/xml-apis.jar com.github.egonw.rednael.LeanderBot
